projects:
  gateway:
    namespace: knative-cd
    description: Temporary Gateway pending kubernetes_gateway support in Terraform
    sourceRepos:
      - "https://github.com/VictortheGreat7/digital-ocean-full-stack.git"
    destinations:
      - server: https://kubernetes.default.svc
        namespace: kube-system
applications:
  cilium-gateway:
    project: gateway
    source:
      repoURL: https://github.com/VictortheGreat7/digital-ocean-full-stack.git
      targetRevision: main
      path: manifests/traffic/gateway
    destination:
      server: https://kubernetes.default.svc
      namespace: kube-system
    syncPolicy:
      automated:
        selfHeal: true
