apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kronos
  namespace: knative-cd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kronos
  source:
    repoURL: https://github.com/VictortheGreat7/digital-ocean-full-stack.git
    targetRevision: main
    path: manifests/kronos-app
  destination:
    server: https://kubernetes.default.svc
    namespace: kronos
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kronos
  namespace: knative-cd
spec:
  description: Project for Kronos World Clock application
  sourceRepos:
    - https://github.com/VictortheGreat7/digital-ocean-full-stack.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: kronos
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
