server:
  httproute:
    enabled: true
    parentRefs: 
      - name: main-gateway
        namespace: kube-system
        sectionName: https
    hostnames:
      - "${kronos_domain}"
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /kcd/argo
        backendRefs:
          - name: argocd-server
            port: 80
configs:
  params:
    server.basehref: /kcd/argo
    server.rootpath: /kcd/argo
    server.insecure: true

