prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: "60m"
        memory: "500Mi"
      limits:
        cpu: "70m"
        memory: "600Mi"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: do-block-storage
          resources:
            requests:
              storage: 10Gi
    enableRemoteWriteReceiver: true
    enableFeatures:
      - native-histograms
      - exemplar-storage
    routePrefix: "/"
  route:
    main:
      enabled: true
      parentRefs:
        - name: main-gateway
          namespace: kube-system
          sectionName: https
      matches:
        - path:
            type: PathPrefix
            value: /monitoring/prometheus
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /

alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        cpu: "2m"
        memory: "64Mi"
      limits:
        cpu: "3m"
        memory: "96Mi"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: do-block-storage
          resources:
            requests:
              storage: 10Gi
    routePrefix: "/"
  route:
    main:
      enabled: true
      parentRefs:
        - name: main-gateway
          namespace: kube-system
          sectionName: https
      matches:
        - path:
            type: PathPrefix
            value: /monitoring/alertmanager
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /

grafana:
  persistence:
    enabled: true
    storageClassName: do-block-storage
    size: 10Gi
  resources:
    limits:
      cpu: "40m"
      memory: "256Mi"
    requests:
      cpu: "20m"
      memory: "160Mi"
  sidecar:
    resources:
      limits:
        cpu: "40m"
        memory: "160Mi"
      requests:
        cpu: "20m"
        memory: "96Mi"
  adminPassword: admin
  grafana.ini:
    server:
      serve_from_sub_path: true
  route:
    main:
      enabled: true
      parentRefs:
        - name: main-gateway
          namespace: kube-system
          sectionName: https
      matches:
        - path:
            type: PathPrefix
            value: /monitoring/grafana
