# apiVersion: v1
# kind: Secret
# metadata:
#   name: datadog-api-key
#   namespace: monitoring
# type: Opaque
# data:
#   api-key: API-KEY
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: datadog-app-key
#   namespace: monitoring
# type: Opaque
# data:
#   app-key: APP-KEY