apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kronos-to-datadog
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: datadog
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kronos
    toPorts:
    - ports:
      - port: "4318"
        protocol: TCP