---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: datadog-agent-netpol
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app: datadog
  ingress:
    - fromEntities:
        - cluster
        - host
        - remote-node
      toPorts:
      - ports:
        - port: "4317"
          protocol: TCP
        - port: "4318"
          protocol: TCP
        - port: "8125"
          protocol: UDP
        - port: "8126"
          protocol: TCP
        - port: "5555"
          protocol: TCP

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-netpol
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  ingress:
    - fromEntities:
        - cluster
        - host
        - remote-node
      toPorts:
      - ports:
        - port: "9090"
          protocol: TCP
        - port: "8080"
          protocol: TCP

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: grafana-netpol
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  ingress:
    - fromEntities:
        - cluster
        - world
        - host
        - remote-node
      toPorts:
      - ports:
        - port: "80"
          protocol: TCP
        - port: "3000"
          protocol: TCP

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: alertmanager-netpol
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
  ingress:
    - fromEntities:
        - cluster
      toPorts:
      - ports:
        - port: "9093"
          protocol: TCP
        - port: "9094"
          protocol: ANY
        - port: "8080"
          protocol: TCP

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: node-exporter-netpol
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus-node-exporter
  ingress:
    - fromEntities:
        - cluster
        - host
        - remote-node
      toPorts:
      - ports:
        - port: "9100"
          protocol: TCP

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kube-state-metrics-netpol
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  ingress:
    - fromEntities:
        - cluster
      toPorts:
      - ports:
        - port: "8080"
          protocol: TCP

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: datadog-cluster-agent-netpol
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app: datadog-cluster-agent
  ingress:
    - fromEntities:
        - cluster
        - host
        - remote-node
      toPorts:
      - ports:
        - port: "5005"
          protocol: TCP
        - port: "443"
          protocol: TCP

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-operator-netpol
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
  ingress:
    - fromEntities:
        - cluster
        - host
        - remote-node
      toPorts:
      - ports:
        - port: "443"
          protocol: TCP
        - port: "8443"
          protocol: TCP
        - port: "10250"
          protocol: TCP
