---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: datadog-agent-netpol
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app: datadog
  ingress:
    - fromEndpoints:
      - matchLabels: {}
      - matchExpressions:
        - key: "k8s:io.kubernetes.pod.namespace"
          operator: Exists
      fromEntities:
        - host
        - remote-node
        - cluster
      toPorts:
      - ports:
        - port: "4317"
          protocol: TCP
        - port: "4318"
          protocol: TCP
        - port: "8125"
          protocol: UDP
        - port: "8126"
          protocol: TCP
        - port: "5555"
          protocol: TCP
  egress:
    - toEndpoints:
      - matchExpressions:
        - key: "k8s:io.kubernetes.pod.namespace"
          operator: Exists
    - toEntities:
        - world
        - host
        - remote-node
        - cluster
        - all

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-netpol
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  ingress:
    - fromEndpoints:
      - matchExpressions:
        - key: "k8s:io.kubernetes.pod.namespace"
          operator: Exists
      fromEntities:
        - host
        - remote-node
      toPorts:
      - ports:
        - port: "9090"
          protocol: TCP
        - port: "8080"
          protocol: TCP
  egress:
    - toEndpoints:
      - matchExpressions:
        - key: "k8s:io.kubernetes.pod.namespace"
          operator: Exists
    - toEntities:
        - world
        - host
        - remote-node
        - cluster
        - all

