apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: github-secret-store
spec:
  provider:
  pulumi:
      organization: VictortheGreat7-org
      project: <NAME_OF_THE_PROJECT>
      environment: kronos
      accessToken:
        secretRef:
          name: pulumi-token
          key: token
          namespace: secrets