projects:
  kronos:
    namespace: knative-cd
    description: Project for Kronos World Clock application
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "4"
    sourceRepos:
      - "https://github.com/VictortheGreat7/digital-ocean-full-stack.git"
    destinations:
      - server: https://kubernetes.default.svc
        namespace: kronos
    clusterResourceWhitelist:
    - group: ''
      kind: Namespace
applications:
  kronos:
    namespace: knative-cd
    project: kronos
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "5"
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
    source:
      repoURL: https://github.com/VictortheGreat7/digital-ocean-full-stack.git
      targetRevision: main
      path: manifests/kronos-app
    destination:
      server: https://kubernetes.default.svc
      namespace: kronos
