projects:
  chaos-testing:
    namespace: knative-cd
    description: Project for chaos testing applications
    sourceRepos:
      - "https://github.com/VictortheGreat7/digital-ocean-full-stack.git"
      - "https://grafana.github.io/helm-charts"
    destinations:
      - server: https://kubernetes.default.svc
        namespace: chaos
      - server: https://kubernetes.default.svc
        namespace: default
      - server: https://kubernetes.default.svc
        namespace: monitoring
    clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
applications:
  chaos-operator:
    namespace: knative-cd
    project: chaos-testing
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
    sources:
      - repoURL: https://github.com/VictortheGreat7/digital-ocean-full-stack.git
        targetRevision: main
        ref: values
      - repoURL: https://grafana.github.io/helm-charts
        chart: k6-operator
        targetRevision: 4.2.0
        helm:
          valueFiles:
            - $values/helm/chaos-operator/values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: chaos

  chaos-test:
    namespace: knative-cd
    project: chaos-testing
    annotations:
      argocd.argoproj.io/depends-on: chaos-operator
    syncPolicy:
      automated:
        selfHeal: false
    source:
      repoURL: https://github.com/VictortheGreat7/digital-ocean-full-stack.git
      targetRevision: main
      path: manifests/chaos-testing
    destination:
      server: https://kubernetes.default.svc
      namespace: chaos
  