projects:
  monitoring:
    namespace: knative-cd
    description: Project for monitoring applications
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "0"
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    sourceRepos:
      - "https://github.com/VictortheGreat7/digital-ocean-full-stack.git"
      - "https://github.com/prometheus-operator/kube-prometheus"
      - "https://prometheus-community.github.io/helm-charts"
      - "https://helm.datadoghq.com"
    destinations:
      - server: https://kubernetes.default.svc
        namespace: monitoring
      - server: https://kubernetes.default.svc
        namespace: kube-system
    clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    - group: '*'
      kind: ValidatingWebhookConfiguration
    - group: '*'
      kind: MutatingWebhookConfiguration

applications:
  otel-config:
    namespace: knative-cd
    project: monitoring
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "1"
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
    source:
      repoURL: https://github.com/VictortheGreat7/digital-ocean-full-stack.git
      targetRevision: main
      path: manifests/monitoring/
    destination:
      server: https://kubernetes.default.svc
      namespace: monitoring

  kube-prom-stack:
    namespace: knative-cd
    project: monitoring
    additionalAnnotations:
      argocd.argoproj.io/depends-on: "otel-config"
      argocd.argoproj.io/sync-wave: "2"
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    syncPolicy:
      automated:
        selfHeal: false
      syncOptions:
        - ServerSideApply=true
    sources:
      - repoURL: https://github.com/VictortheGreat7/digital-ocean-full-stack.git
        targetRevision: main
        ref: values
      - repoURL: https://prometheus-community.github.io/helm-charts
        chart: kube-prometheus-stack
        targetRevision: 81.6.7
        helm:
          valueFiles:
            - $values/argocd-helm/kube-prom-stack/values.yaml
          parameters:
            - name: prometheus.prometheusSpec.externalUrl
              value: "https://${hostname}/monitoring/prometheus/"
            - name: prometheus.route.main.hostnames[0]
              value: ${hostname}
            - name: alertmanager.alertmanagerSpec.externalUrl
              value: "https://${hostname}/monitoring/alertmanager/"
            - name: alertmanager.route.main.hostnames[0]
              value: ${hostname}
            - name: grafana.grafana\.ini.server.root_url
              value: "https://${hostname}/monitoring/grafana/"
            - name: grafana.route.main.hostnames[0]
              value: ${hostname}
    destination:
      server: https://kubernetes.default.svc
      namespace: monitoring

  datadog:
    namespace: knative-cd
    project: monitoring
    additionalAnnotations:
      argocd.argoproj.io/depends-on: "otel-config"
      argocd.argoproj.io/sync-wave: "3"
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
        - ServerSideApply=true
    sources:
      - repoURL: https://github.com/VictortheGreat7/digital-ocean-full-stack.git
        targetRevision: main
        ref: values
      - repoURL: https://helm.datadoghq.com
        chart: datadog
        targetRevision: 3.170.1
        helm:
          valueFiles:
            - $values/argocd-helm/datadog/values.yaml
          parameters:
            - name: datadog.clusterName
              value: ${cluster_name} # Terraform-set cluster name
    destination:
      server: https://kubernetes.default.svc
      namespace: monitoring
