apiVersion: apps/v1
kind: Deployment
metadata:
  name: kronos-backend
  namespace: kronos
  labels:
    app: kronos-app
    component: backend
    environment: development
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: kronos-app
      component: backend
      environment: development
  template:
    metadata:
      labels:
        app: kronos-app
        component: backend
        environment: development
    spec:
      containers:
        - name: backend
          image: victorthegreat7/kronos-backend:latest
          env:
            - name: OTEL_SERVICE_NAME
              value: kronos-backend
            - name: OTEL_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OTEL_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OTEL_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: DEPLOYMENT_ENV
              value: dev
            - name: SERVICE_VERSION
              value: 1.0.0
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://datadog.monitoring.svc.cluster.local:4317
            - name: OTLP_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=$(SERVICE_VERSION),deployment.environment=$(DEPLOYMENT_ENV),service.name=$(OTEL_SERVICE_NAME),k8s.namespace.name=$(OTEL_K8S_NAMESPACE),k8s.pod.name=$(OTEL_K8S_POD_NAME),host.name=$(OTEL_K8S_NODE_NAME)
            - name: DB_HOST
              value: kronos-postgres-0.kronos-postgres-svc.kronos.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: kronos
            - name: DB_USER
              value: app
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: 256Mi
              cpu: 300m
            limits:
              memory: 288Mi
              cpu: 400m
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
