apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kronos-postgres
  namespace: kronos
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: kronos-app
      component: db
      environment: development
  template:
    metadata:
      labels:
        app: kronos-app
        component: db
        environment: development
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: kronos
            - name: POSTGRES_USER
              value: app
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U app -d kronos
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: init-script
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 20Gi
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
